---
- hosts: all
  become: true
  become_user: root
  become_method: su

  roles:
    - upgrade
    - ntp
    - pkg
    - login_conf
    - rc
    - doas
    - packages
    - sshd
    - sysctl
    - fail2ban
    - hushlogin
    - loader
    - ports
    - reboot