---
- name: Latest | Creating pkg repos directory
  ansible.builtin.file:
    path: /usr/local/etc/pkg/repos
    state: directory
    mode: '0755'
  when: use_latest_packages

- name: Latest | Copy pkg repo configuration file
  ansible.builtin.copy:
    src: /etc/pkg/FreeBSD.conf
    dest: /usr/local/etc/pkg/repos/FreeBSD.conf
    owner: root
    group: wheel
    mode: '0644'
    force: false
    remote_src: yes
  when: use_latest_packages

- name: Latest | Setting up latest pkg repo
  replace:
    path: /usr/local/etc/pkg/repos/FreeBSD.conf
    regexp: 'quarterly'
    replace: 'latest'
  when: use_latest_packages

- name: Update package cache
  shell: pkg update -f

- name: Update audit database
  shell: pkg audit -F

- name: Upgrade all packages
  community.general.pkgng:
    name: "*"
    state: latest