---
- name: Setting up pkg repository (1/2)
  ansible.builtin.file:
    path: /usr/local/etc/pkg/repos
    state: directory
    mode: '0755'

- name: Setting up pkg repository (1/2)
  copy: 
    src: Latest.conf
    dest: /usr/local/etc/pkg/repos/Latest.conf
    mode: '0644'

- name: Installing pkg
  shell: yes | pkg
  ignore_errors: yes

- name: Updating package cache
  shell: pkg update -f

- name: Updating vulnerability db
  shell: pkg audit -F