---
- name: Installing Fail2Ban
  community.general.pkgng:
    name: py39-fail2ban
    state: present

- name: Copying config file (Fail2Ban)
  template: 
    src: jail.local.j2 
    dest: /usr/local/etc/fail2ban/jail.local
    mode: '0640'

- name: Enable Fail2Ban
  shell: sysrc -f /etc/rc.conf.local fail2ban_enable="YES"